# Generated by Django 6.0.5 on 2026-05-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_alimento', models.CharField(max_length=150)),
                ('quantidade', models.IntegerField()),
                ('data_validade', models.DateField()),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
