# Generated by Django 6.0.5 on 2026-06-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='destino',
            field=models.CharField(default='Estoque Interno', max_length=150),
        ),
    ]
